# Generated by Django 5.1.3 on 2024-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('op1', models.CharField(max_length=20)),
                ('op2', models.CharField(max_length=20)),
                ('op3', models.CharField(max_length=20)),
                ('op4', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
